# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "preview"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "pierskarsenbarg/githubapp-test"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  echo: 
    title: Test variables
    image: alpine
    commands:
      - echo $CF_BRANCH

  preview:
    title: "Preview Pulumi"
    image: "pulumi/pulumi" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
          - npm install
          - pulumi login
          - pulumi stack select dev
          - pulumi preview
    stage: "preview"

